### ISSUE TITLE
Using a dataset other than "production" isn't currently possible with metalsmith-sanity

### ISSUE THREAD

**Issue by nielthiart** [hdoro/metalsmith-sanity#1]
@hdoro thanks for this useful plugin.

Any dataset name and token entered in config is not used when building the data export URL used for fetching data from sanity.

The dataset from config should be used when creating the URL here: https://github.com/hdoro/metalsmith-sanity/blob/a6b0168d8a3f08c558333402b87224e33b306e7e/importFromSanity/index.js#L37

The token from config should be passed as a parameter here: https://github.com/hdoro/metalsmith-sanity/blob/a6b0168d8a3f08c558333402b87224e33b306e7e/importFromSanity/index.js#L43

**Comment by hdoro** [comment]
Thanks so much for this, @nielthiart , the change is live on npm!

Quick question: did you find a solid workflow for developing in Metalsmith? I love how easy it is to build stuff, but working on the front-end was painstakingly hard and slow as have to re-build the whole website on every change (I was using `metalsmith-watch`, if I'm not mistaken). Would love to get a better insight on this 😄

**Comment by nielthiart** [comment]
Thanks for the merge!

> Quick question: did you find a solid workflow for developing in Metalsmith?

I wish I could say I have, but it is quite cumbersome and inefficient. I'm making a really old static site dynamic, and at this point giving editors the ability to change content is top priority. I'll likely move on to a more modern static site generator for this site once existing content is up to date.

Yes, I'm also using `metalsmith-watch` and basically rebuilding *everything* from scratch for each change in development. On the live build server we're only building on deliberate request from the editors so there's no preview. Still quite inefficiently rebuilding everything but at least debouncing concurrent rebuild+deploy requests from editors.

**Comment by hdoro** [comment]
Thank you for the thorough answer, Niel! Well, I guess metalsmith isn't well suited for more complex sites, then. It's a bummer, its API is the simplest and most flexible out there for those who need control over everything.

Good luck on this project, I'm sure editors will be super happy with Sanity 😄

**Comment by nielthiart** [comment]
Yeah Metalsmith really is the simplest out there - why we chose it way back. :smile: 

I'm sure builds can be optimised by using https://github.com/axa-ch/metalsmith-incremental and fine-tuning globbing patterns for `metalsmith-watch` - I might try these out as a stopgap, but it looks like it might make things a bit more complex.
